### ISSUE TITLE
Create brand guidelines 

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/brand#11]
As the Vega team or community member
I want to be able to understand how to use the Vega brand and it's assets
So that I can easily and effectively create projects that look and feel like part of the Vega ecosystem  

**Acceptance Criteria**

- I can read about how to use the Vega brand - including logo, typography, visual styles etc.
- I can find and use all the key brand assets in the brand repo 
- I can learn about the Vega Tone of Voice and examples of it's use
- I am pointed in the direction of external tools to help me implement the brand i.e. Figma Design System, Storybook etc.

**Comment by bigfandavid** [comment]
@pennyandrews - Keen to get going on this. Do we know who is overseeing this from Vega's side? 

I think an initial kick-off meeting would be useful to go through Mary's approach. Mary and I have spoken about it, but need clarification the approach is correct.

**Comment by maryvaliakas** [comment]
> 

@bigfandavid I've spoken with Nissa about this. She would be the one owning this. She's yet to review the document what with everything going on. We can come together and form a view of what we might like it to look like to try and move the needle on it a little bit.

**Comment by bigfandavid** [comment]
Ahh okay great. @maryvaliakas please could you drop the doc link here so I can access it? My bookmarks are very unwieldy at the moment :P I'll take a look through and put some thoughts together.

**Comment by maryvaliakas** [comment]
Sure thing @bigfandavid here you go https://docs.google.com/document/d/1FmM2dKXXf34fxSgo-5cFVfNVfrZGo0gf7PquXPPh9JE/edit?usp=sharing
